### PR TITLE
Contributors

### PR DESCRIPTION
**Pull request by gkellogg**
Editors and contributors.

@pchampin: please add @timothee-haudebourg as a contributor to this repo.

***

### :boom: Error: 500 Internal Server Error :boom: ###

[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Feb 3, 2023, 1:03 AM UTC)_.

<details>
<summary>More</summary>

PR Preview relies on a number of web services to run. There seems to be an issue with the following one:

:rotating_light: [Spec Generator](https://www.w3.org/2015/labs/) - Spec Generator is the web service used to build specs that rely on ReSpec.

:link: [Related URL](https://labs.w3.org/spec-generator/?type=respec&url=https%3A%2F%2Fraw.githubusercontent.com%2Fw3c%2Frdf-schema%2F493703cd99e8df4929e08256cce1fae6a7da604c%2Fspec%2Findex.html%3FisPreview%3Dtrue)

```

😭  Sorry, there was an error generating the HTML. Please report this issue!
Specification: http://labs.w3.org/spec-generator/uploads/pYnu0D/spec/index.html?isPreview=true%3FisPreview%3Dtrue&publishDate=2023-02-03
ReSpec version: 32.7.0
File a bug: https://github.com/w3c/respec/
Error: Error: Evaluation failed: Timeout: document.respec.ready didn't resolve in 25932ms.
    at ExecutionContext._ExecutionContext_evaluate (/u/spec-generator/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:229:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ExecutionContext.evaluate (/u/spec-generator/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:107:16)
    at async generateHTML (/u/spec-generator/node_modules/respec/tools/respecDocWriter.js:221:12)
    at async toHTML (/u/spec-generator/node_modules/respec/tools/respecDocWriter.js:92:18)
    at async Object.generate [as respec] (file:///u/spec-generator/generators/respec.js:15:44)
    at async file:///u/spec-generator/server.js:252:48

```

_If you don't have enough information above to solve the error by yourself (or to understand to which web service the error is related to, if any), please [file an issue](https://github.com/tobie/pr-preview/issues/new?title=Error%20not%20surfaced%20properly&body=See%20w3c/rdf-schema%234.)._
</details>

### CODE REVIEW

**Comment by gkellogg** [comment]
PR Preview still failed, hopefully won't for future PRs. In the mean time, you can read the formatted document via GitHack: https://raw.githack.com/w3c/rdf-schema/contributors/spec/index.html

**Review by domel — COMMENTED** [review]
In A.3., the last last name is written in capital letters.

**Comment by gkellogg** [comment]
> In A.3., the last last name is written in capital letters.

Yes, that's because @timothee-haudebourg's record on W3C is written that way, so that's how it is downloaded from the API. If @timothee-haudebourg updates it, we can re-generate the participants, which we'll do from time-to-time in any case.

**Review by domel — APPROVED** [review]

**Review by domel — APPROVED** [review]

**Comment by timothee-haudebourg** [comment]
> Yes, that's because @timothee-haudebourg's record on W3C is written that way, so that's how it is downloaded from the API.

I've updated my name so next time it is generated it should not be in all caps.

**Review by timothee-haudebourg — APPROVED** [review]

**Pull request merged**
